# Generated by Django 4.2.21 on 2025-05-11 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='admin_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Admin ID must contain only uppercase letters and numbers.', regex='^[A-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Course ID must contain only uppercase letters and numbers.', regex='^[A-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Credits must be at least 1.'), django.core.validators.MaxValueValidator(10, message='Credits cannot exceed 10.')]),
        ),
    ]
