# Generated by Django 4.2.21 on 2025-05-11 07:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION', 'Đăng ký học phần'), ('SCHEDULE', 'Lịch học'), ('GRADE', 'Điểm số'), ('SYSTEM', 'Hệ thống'), ('OTHER', 'Khác')], max_length=20, validators=[django.core.validators.RegexValidator(message='Notification type must be one of: REGISTRATION, SCHEDULE, GRADE, SYSTEM, OTHER.', regex='^(REGISTRATION|SCHEDULE|GRADE|SYSTEM|OTHER)$')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Title must contain only letters, numbers, spaces, and basic punctuation.', regex='^[A-Za-z0-9\\s\\-_.,!?()]+$')]),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('registration_notifications', models.BooleanField(default=True)),
                ('schedule_notifications', models.BooleanField(default=True)),
                ('grade_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
