# Generated by Django 4.2.21 on 2025-05-11 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='schedule',
            name='capacity',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1, message='Capacity must be at least 1.'), django.core.validators.MaxValueValidator(200, message='Capacity cannot exceed 200.')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='academic_year',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Academic year must be in the format: "2023-2024".', regex='^\\d{4}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Thứ Hai'), ('TUE', 'Thứ Ba'), ('WED', 'Thứ Tư'), ('THU', 'Thứ Năm'), ('FRI', 'Thứ Sáu'), ('SAT', 'Thứ Bảy'), ('SUN', 'Chủ Nhật')], max_length=3, validators=[django.core.validators.RegexValidator(message='Day of week must be one of: MON, TUE, WED, THU, FRI, SAT, SUN.', regex='^(MON|TUE|WED|THU|FRI|SAT|SUN)$')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Room must contain only letters, numbers, spaces, and hyphens.', regex='^[A-Za-z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Semester must contain only letters, numbers, and spaces.', regex='^[A-Za-z0-9\\s]+$')]),
        ),
    ]
